Repository VibrentHealth/keycloak-operator, pull requests merged in 2021-05, with the labels that each got.

#5 feat(ci): Added Jenkinsfile
  Dockerfile
  Jenkinsfile
  README.md
  charts/keycloak-operator/README.md
Labels: ready for review, size/L

#6 feature(CI): Variable dockerfile FROM for github actions
  Dockerfile
  Jenkinsfile
  Makefile
  README.md
Labels: ready for review, size/S

#7 feat(chart): Update helm chart to accept imagePullsecret values
  charts/keycloak-operator/templates/operator.yaml
  charts/keycloak-operator/values.yaml
Labels: size/XS
