Repository VibrentHealth/keycloak-operator, pull requests merged in 2022-07, with the labels that each got.

#14 fix(kc): AC-120153 Support for the operator to merge a new client def with an existing real client.
  README.md
  charts/keycloak-operator/Chart.yaml
  deploy/examples/keycloak/external-keycloak.yaml
  deploy/examples/realm/basic_realm.yaml
  deploy/operator.yaml
  pkg/common/client_state.go
Labels: ready for review, size/XL

#16 feat(headers): add support for the browserSecurityHeaders
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/crds/keycloak.org_keycloakrealms_crd.yaml
  deploy/crds/keycloak.org_keycloakrealms_crd.yaml
  pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  test/e2e/keycloak_realm_test.go
Labels: enhancement, size/M

#17 fix(readme): update readme to include the browser security headers support
  README.md
Labels: enhancement, size/XS

#18 fix(programId): string -> int
  charts/keycloak-operator/Chart.yaml
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  pkg/common/cluster_actions.go
Labels: enhancement, size/XS

#20 feat(CRD): Add Required Actions list to KeycloakRealm CRD
  README.md
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/crds/keycloak.org_keycloakrealms_crd.yaml
  deploy/crds/keycloak.org_keycloakrealms_crd.yaml
  pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
Labels: do not merge, enhancement, size/L

#21 fix(client): Convert URLs from program configuration to lower case
  charts/keycloak-operator/Chart.yaml
  pkg/common/client_state.go
  pkg/common/cluster_actions.go
Labels: bug, do not merge, ready for review, size/M
